#!/bin/bash

# ******************************
# Install minimal lxde desktop *
# ******************************

if [ "$(id -u)" != "0" ]; then
	echo "Script must be run as root !"
	exit 0
fi

echo ""
date
echo -e "\033[36m======================="
echo -e "Installing Mate Desktop"
echo -e "=======================\033[37m"
echo ""

# Check if we have enough disk space.
S=`df / | tail -n 1 | awk '{printf $4}' | sed s/[G,M,K]//g`
if [ "$S" -le "500000" ]; then
	echo "We need at least 500MB free to perform minimal desktop instalation"
	echo "Have you resized your partition (fs_resize)?"
	exit 0
fi

# SET USER NAME !!
_user="odroid"

logfile="mate-install.log"
#logfile=/dev/stdout

#_auto=""
_auto="-y -q"

_DST=`lsb_release -si`
_REL=`lsb_release -sc`

if [ ! "${_REL}" = "jessie" ] && [ ! "${_REL}" = "vivid" ]; then
  echo "Not supported on ${_DST}-${_REL}"
  exit 0
fi

if [ "${_REL}" = "jessie" ] ; then
    # kodi from hardkernel repository needs some lib's from trusty !!!
    echo "APT::Default-Release \"jessie\";" >> /etc/apt/apt.conf.d/70debconf
    echo "deb http://ports.ubuntu.com/ubuntu-ports/ trusty main universe" >> /etc/apt/sources.list
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5 3B4FE6ACC0B21F32 >> $logfile
fi

if [ "${_REL}" = "vivid" ] ; then
    # kodi from hardkernel repository needs some lib's from trusty !!!
    echo "http://ports.ubuntu.com/ubuntu-ports/ trusty main universe" >> $odir/sources.list
fi


echo "Package update..."
apt-get $_auto update >> $logfile
echo "Package upgrade..."
apt-get $_auto upgrade >> $logfile
echo ""

echo "$_DST - $_REL, Installing MATE DESKTOP..."
echo "$_DST - $_REL, Installing MATE DESKTOP..." > $logfile

# === Install base packages =======================================================================================================================================================
echo "  installing base packages, please wait..."
apt-get $_auto install pulseaudio pulseaudio-module-x11 pulseaudio-utils alsa-base alsa-oss alsa-utils alsa-tools libasound2-data aml-libs --no-install-recommends >> $logfile
apt-get clean
apt-get $_auto install gstreamer1.0-pulseaudio mali-x11 xserver-xorg-video-mali >> $logfile
apt-get clean

# === Install desktop =============================================================================================================================================================
echo "  installing Mate desktop, please wait..."
apt-get $_auto install xinit xserver-xorg lightdm lightdm-gtk-greeter policykit-1 --no-install-recommends >> $logfile
apt-get $_auto install mate-desktop-environment pluma engrampa mate-themes mate-system-monitor mate-applets mate-utils atril eom mate-indicator-applet mate-media --no-install-recommends >> $logfile
if [ "${_DST}" = "Ubuntu" ] ; then
    apt-get clean
    apt-get $_auto install language-selector-gnome ubuntu-mate-lightdm-theme lightdm-gtk-greeter-settings mate-tweak indicator-sound --no-install-recommends >> $logfile
fi
apt-get clean

echo "  installing more packages, please wait..."
apt-get $_auto install synaptic software-properties-gtk policykit-1-gnome gksu galculator --no-install-recommends >> $logfile
apt-get $_auto install mesa-utils mesa-utils-extra glmark2-es2 >> $logfile
apt-get clean

# === Install network packages & internet browser =================================================================================================================================
# you don't have to install internet browser, you can save ~100MB
echo "  installing network packages, please wait..."
if [ "${_DST}" = "Ubuntu" ] ; then
    apt-get $_auto install firefox gvfs-fuse gvfs-backends --no-install-recommends >> $logfile
else
    apt-get $_auto install iceweasel gvfs-fuse gvfs-backends libcurl3-gnutls --no-install-recommends >> $logfile
fi
apt-get clean


if [ -f /etc/X11/xorg.conf ]; then
  cp /etc/X11/xorg.conf /usr/local/bin/xorg.conf
fi
apt-get $_auto remove xserver-xorg --purge >> $logfile
apt-get $_auto install xserver-xorg >> $logfile
apt-get clean
if [ -f /usr/local/bin/xorg.conf ]; then
  mv /usr/local/bin/xorg.conf /etc/X11/xorg.conf
fi

if [ -d /usr/local/bin/mali_ddx/${_REL} ]; then
  cp /usr/local/bin/mali_ddx/${_REL}/mali_drv.* /usr/lib/xorg/modules/drivers
fi

# === Configuration ===============================================================================================================================================================
echo ""
echo "Configuring desktop..."

if [ -f /boot/boot.ini ]; then
    cat /boot/boot.ini | sed s/"setenv m_bpp \"16\""/"setenv m_bpp \"32\""/g > /tmp/_bootini
    mv /tmp/_bootini /boot/boot.ini
    cat /boot/boot.ini | sed s/"setenv vpu \"0\""/"setenv vpu \"1\""/g > /tmp/_bootini
    mv /tmp/_bootini /boot/boot.ini
fi

if [ -f /media/boot/boot.ini ]; then
    cat /media/boot/boot.ini | sed s/"setenv m_bpp \"16\""/"setenv m_bpp \"32\""/g > /tmp/_bootini
    mv /tmp/_bootini /media/boot/boot.ini
    cat /media/boot/boot.ini | sed s/"setenv vpu \"0\""/"setenv vpu \"1\""/g > /tmp/_bootini
    mv /tmp/_bootini /media/boot/boot.ini
fi

if [ -f /etc/X11/Xwrapper.config ]; then
    cat /etc/X11/Xwrapper.config | sed s/"allowed_users=console"/"allowed_users=anybody"/g > /tmp/_xwrap
    mv /tmp/_xwrap /etc/X11/Xwrapper.config
fi

echo "Configuring sound"
#*********************
# ** CONFIGURE SOUND
#*********************
cat > /etc/asound.conf << _EOF_
pcm.!default {
  type plug
  slave {
    pcm "hw:0,1"
  }
}
ctl.!default {
  type hw
  card 0
}
_EOF_

if [ -f /etc/pulse/default.pa ]; then
    cat /etc/pulse/default.pa | sed s/"#load-module module-alsa-sink"/"load-module module-alsa-sink"/g > /tmp/default.pa
    mv /tmp/default.pa /etc/pulse/default.pa
    cat /etc/pulse/default.pa | sed s/"#load-module module-alsa-source device=hw:1,0"/"load-module module-alsa-source device=hw:0,1"/g > /tmp/default.pa
    mv /tmp/default.pa /etc/pulse/default.pa
fi


usermod -a -G adm,dialout,cdrom,audio,dip,video,plugdev,netdev,fuse $_user

chown -R $_user:$_user /home/$_user


echo ""
echo "**********************************************"
echo "* MATE DESKTOP INSTALLED, please REBOOT now! *"
echo "**********************************************"
date
echo ""

