#!/bin/bash

# **************************************
# Install typical lubuntu/lxde desktop *
# **************************************

if [ "$(id -u)" != "0" ]; then
	echo "Script must be run as root !"
	exit 0
fi

# Check if we have enough disk space.
S=`df / | tail -n 1 | awk '{printf $4}' | sed s/[G,M,K]//g`
if [ "$S" -le "800000" ]; then
	echo "We need at least 800MB free to perform desktop instalation"
	echo "Have you resized your Partition (fs_resize)?"
	exit 0
fi

# SET USER NAME !!
_user="odroid"

logfile="dinstall.log"
#logfile=/dev/stdout

#_auto=""
_auto="-y -q"
_DST=`lsb_release -si`
_REL=`lsb_release -sc`

if [ "${_REL}" = "wheezy" ] || [ "${_REL}" = "precise" ] || [ "${_REL}" = "vivid" ]; then
    echo "Not supported on ${_DST}-${_REL}"
    exit 0
fi

_mateinst=`dpkg-query -l | grep -o mate-desktop-environment`
if [ ! "${_mateinst}" = "" ]; then
  echo "Not needed with Mate desktop."
  exit 0
fi


echo "$_DST - $_REL, Installing DESKTOP..."
echo "$_DST - $_REL, Installing DESKTOP..." > $logfile

if [ "${_REL}" = "jessie" ] ; then
    # kodi from hardkernel repository needs some lib's from trusty !!!
    echo "APT::Default-Release \"jessie\";" >> /etc/apt/apt.conf.d/70debconf
    echo "deb http://ports.ubuntu.com/ubuntu-ports/ trusty main universe" >> /etc/apt/sources.list
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5 3B4FE6ACC0B21F32 >> $logfile
fi

if [ "${_REL}" = "utopic" ] ; then
    # kodi from hardkernel repository needs some lib's from trusty !!!
    echo "http://ports.ubuntu.com/ubuntu-ports/ trusty main universe" >> $odir/sources.list
fi

echo "Package update..."
apt-get $_auto update >> $logfile
echo "Package upgrade..."
apt-get $_auto upgrade >> $logfile
echo ""

echo "  installing mali, please wait..."
apt-get $_auto install gstreamer1.0-pulseaudio mali-x11 xserver-xorg-video-mali >> $logfile
apt-get clean

echo "  installing metacity window manager packages, please wait..."
if [ "${_REL}" = "trusty" ] ; then
  apt-get $_auto install dmz-cursor-theme metacity metacity-themes dconf-editor >> $logfile
else
  apt-get $_auto install dmz-cursor-theme dconf-editor >> $logfile
  apt-get $_auto install -t trusty metacity metacity-themes >> $logfile
  apt-mark hold metacity* >> $logfile
fi
apt-get clean
echo "  installing mesa utils, please wait..."
if [ ! "${_REL}" = "jessie" ] ; then
    apt-get $_auto install mesa-utils mesa-utils-extra glmark2-es2 >> $logfile
else
    apt-get $_auto install mesa-utils mesa-utils-extra >> $logfile
fi
apt-get clean
echo "  installing multimedia, please wait..."
if [ ! "${_REL}" = "jessie" ] ; then
    apt-get $_auto install libgnutls26 kodi gnome-mplayer >> $logfile
else
    apt-get $_auto install libgnutls26 kodi
fi
apt-get clean

#echo "  installing office tools, please wait..."
#apt-get $_auto install caligra systemsettings >> $logfile
#apt-get clean


echo ""
echo "Configuring desktop..."
if [ -f /etc/X11/xorg.conf ]; then
    _ok=`cat /etc/X11/xorg.conf | grep IgnoreABI`
    if [ "${_ok}" = "" ] ; then
	echo "  patching xorg.conf"
	cat /etc/X11/xorg.conf | sed '/Section "ServerFlags"/a\        Option          "IgnoreABI"     "true"' > /tmp/_xorg
	mv /tmp/_xorg /etc/X11/xorg.conf
    else
	echo "  xorg.conf allready pached."
    fi
else
    echo "  xorg.conf NOT FOUND !"
fi


# Configure metacity & pcmanfm
echo "  configuring windows manager"
#gsettings set org.gnome.desktop.wm.preferences theme Lubuntu-dark-panel

if [ "${_DST}" = "Ubuntu" ] ; then
    cat /etc/xdg/lxsession/Lubuntu/desktop.conf | sed s/"windows_manager\/command=openbox"/"windows_manager\/command=metacity"/g > /tmp/_desktop.conf
    mv /tmp/_desktop.conf /etc/xdg/lxsession/Lubuntu/desktop.conf
    if [ "${_REL}" = "utopic" ] ; then
      cat /usr/share/glib-2.0/schemas/org.gnome.desktop.wm.preferences.gschema.xml | sed s/"\      <default>'Adwaita'<\/default>"/"\      <default>'Lubuntu-dark-panel'<\/default>"/g > /tmp/_schema
      mv /tmp/_schema /usr/share/glib-2.0/schemas/org.gnome.desktop.wm.preferences.gschema.xml

      _ok=`cat /usr/share/glib-2.0/schemas/org.gnome.metacity.gschema.xml | grep "<default>true<" | wc -l`
      if [ $_ok -eq 1 ]; then
	cat /usr/share/glib-2.0/schemas/org.gnome.metacity.gschema.xml | sed s/"<default>false<\/default>"/"<default>xxxx<\/default>"/g > /tmp/_schema
	mv /tmp/_schema /usr/share/glib-2.0/schemas/org.gnome.metacity.gschema.xml
	cat /usr/share/glib-2.0/schemas/org.gnome.metacity.gschema.xml | sed s/"<default>true<\/default>"/"<default>false<\/default>"/g > /tmp/_schema
	mv /tmp/_schema /usr/share/glib-2.0/schemas/org.gnome.metacity.gschema.xml
	cat /usr/share/glib-2.0/schemas/org.gnome.metacity.gschema.xml | sed s/"<default>xxxx<\/default>"/"<default>true<\/default>"/g > /tmp/_schema
	mv /tmp/_schema /usr/share/glib-2.0/schemas/org.gnome.metacity.gschema.xml
      fi
    else
      cat /usr/share/glib-2.0/schemas/org.gnome.desktop.wm.preferences.gschema.xml | sed s/"\      <default>'Adwaita'<\/default>"/"\      <default>'Metabox'<\/default>"/g > /tmp/_schema
      mv /tmp/_schema /usr/share/glib-2.0/schemas/org.gnome.desktop.wm.preferences.gschema.xml
    fi

    echo "  configuring file manager"
    cat /etc/xdg/pcmanfm/lubuntu/pcmanfm.conf | sed s/"mount_on_startup=1"/"mount_on_startup=0"/g > /tmp/_pcmanfm.conf
    mv /tmp/_pcmanfm.conf /etc/xdg/pcmanfm/lubuntu/pcmanfm.conf
    cat /etc/xdg/pcmanfm/lubuntu/pcmanfm.conf | sed s/"mount_removable=1"/"mount_removable=0"/g > /tmp/_pcmanfm.conf
    mv /tmp/_pcmanfm.conf /etc/xdg/pcmanfm/lubuntu/pcmanfm.conf

    mv /wallpaper.png /usr/share/lubuntu/wallpapers/lubuntu-default-wallpaper.png > /dev/null 2>&1
else
    cat /etc/xdg/lxsession/LXDE/desktop.conf | sed s/"window_manager=openbox-lxde"/"window_manager=metacity"/g > /tmp/_desktop.conf
    mv /tmp/_desktop.conf /etc/xdg/lxsession/LXDE/desktop.conf

    cat /usr/share/glib-2.0/schemas/org.gnome.metacity.gschema.xml | sed s/"<default>false<\/default>"/"<default>xxxx<\/default>"/g > /tmp/_schema
    mv /tmp/_schema /usr/share/glib-2.0/schemas/org.gnome.metacity.gschema.xml
    cat /usr/share/glib-2.0/schemas/org.gnome.metacity.gschema.xml | sed s/"<default>true<\/default>"/"<default>false<\/default>"/g > /tmp/_schema
    mv /tmp/_schema /usr/share/glib-2.0/schemas/org.gnome.metacity.gschema.xml
    cat /usr/share/glib-2.0/schemas/org.gnome.metacity.gschema.xml | sed s/"<default>xxxx<\/default>"/"<default>true<\/default>"/g > /tmp/_schema
    mv /tmp/_schema /usr/share/glib-2.0/schemas/org.gnome.metacity.gschema.xml
fi

echo ""
echo "**********************************************"
echo "* Mali & media installed, please REBOOT now! *"
echo "**********************************************"
echo ""

